In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import zipfile
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
p1 = Path.cwd() / 'data'

In [3]:
college = pd.read_csv(p1 / 'college.csv', index_col='INSTNM')
college.head()

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
Alabama A & M University,Normal,AL,1.0,0.0,0.0,0,424.0,420.0,0.0,4206.0,...,0.0000,0.0059,0.0138,0.0656,1,0.7356,0.8284,0.1049,30300,33888
University of Alabama at Birmingham,Birmingham,AL,0.0,0.0,0.0,0,570.0,565.0,0.0,11383.0,...,0.0368,0.0179,0.0100,0.2607,1,0.3460,0.5214,0.2422,39700,21941.5
Amridge University,Montgomery,AL,0.0,0.0,0.0,1,NaN,NaN,1.0,291.0,...,0.0000,0.0000,0.2715,0.4536,1,0.6801,0.7795,0.8540,40100,23370
University of Alabama in Huntsville,Huntsville,AL,0.0,0.0,0.0,0,595.0,590.0,0.0,5451.0,...,0.0172,0.0332,0.0350,0.2146,1,0.3072,0.4596,0.2640,45500,24097
Alabama State University,Montgomery,AL,1.0,0.0,0.0,0,425.0,430.0,0.0,4811.0,...,0.0098,0.0243,0.0137,0.0892,1,0.7347,0.7554,0.1270,26600,33118.5

In [5]:
city = college['CITY']
city

INSTNM
Alabama A & M University                                            Normal
University of Alabama at Birmingham                             Birmingham
Amridge University                                              Montgomery
University of Alabama in Huntsville                             Huntsville
Alabama State University                                        Montgomery
                                                                ...
SAE Institute of Technology  San Francisco                      Emeryville
Rasmussen College - Overland Park                            Overland Park
National Personal Training Institute of Cleveland         Highland Heights
Bay Area Medical Academy - San Jose Satellite Location            San Jose
Excel Learning Center-San Antonio South                        San Antonio
Name: CITY, Length: 7535, dtype: object

In [7]:
alabama = city.isin(['Birmingham', 'Montgomery'])
city[alabama]

INSTNM
University of Alabama at Birmingham                 Birmingham
Amridge University                                  Montgomery
Alabama State University                            Montgomery
Auburn University at Montgomery                     Montgomery
Birmingham Southern College                         Birmingham
South University-Montgomery                         Montgomery
Faulkner University                                 Montgomery
Herzing University-Birmingham                       Birmingham
Huntingdon College                                  Montgomery
Jefferson State Community College                   Birmingham
Lawson State Community College-Birmingham Campus    Birmingham
Samford University                                  Birmingham
Southeastern Bible College                          Birmingham
H Councill Trenholm State Community College         Montgomery
West Virginia University Institute of Technology    Montgomery
Virginia College-Birmingham                         Birmingham
Southeastern School of Cosmetology                  Birmingham
Strayer University-Alabama                          Birmingham
University of Phoenix-Alabama                       Birmingham
Virginia College-Montgomery                         Montgomery
Fortis College-Montgomery                           Montgomery
Fortis Institute-Birmingham                         Birmingham
Hair Academy                                        Montgomery
Brown Mackie College-Birmingham                     Birmingham
Nunation School of Cosmetology                      Birmingham
Troy University-Montgomery Campus                   Montgomery
Name: CITY, dtype: object

In [9]:
city['Alabama A & M University':'Alabama State University'], city.loc['Alabama A & M University':'Alabama State University']

(INSTNM
 Alabama A & M University                   Normal
 University of Alabama at Birmingham    Birmingham
 Amridge University                     Montgomery
 University of Alabama in Huntsville    Huntsville
 Alabama State University               Montgomery
 Name: CITY, dtype: object,
 INSTNM
 Alabama A & M University                   Normal
 University of Alabama at Birmingham    Birmingham
 Amridge University                     Montgomery
 University of Alabama in Huntsville    Huntsville
 Alabama State University               Montgomery
 Name: CITY, dtype: object)

In [11]:
city.loc['Alabama State University':'Alabama A & M University':-1]

INSTNM
Alabama State University               Montgomery
University of Alabama in Huntsville    Huntsville
Amridge University                     Montgomery
University of Alabama at Birmingham    Birmingham
Alabama A & M University                   Normal
Name: CITY, dtype: object

In [14]:
college.iloc[60, :].equals(college.loc['University of Alaska Anchorage', :])

True

In [16]:
start = 'Empire Beauty School-Flagstaff'
stop = 'Arizona State University-Tempe'
college.loc[start:stop:-1, :]

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
Empire Beauty School-Flagstaff,Flagstaff,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,60.0,...,0.0333,0.0000,0.0000,0.0000,1,0.7381,0.6786,0.3208,17800,10050
Cochise County Community College District,Douglas,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,3759.0,...,0.0229,0.0040,0.0213,0.5539,1,0.3360,0.0721,0.4534,28600,6500
Charles of Italy Beauty College,Lake Havasu City,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,54.0,...,0.0000,0.0000,0.0000,0.0000,1,0.7405,0.6107,0.4819,14500,7389
Brown Mackie College-Tucson,Tucson,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,611.0,...,0.0000,0.0000,0.0098,0.0000,1,0.8567,0.7895,0.6520,27400,22141.5
Central Arizona College,Coolidge,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,5275.0,...,0.0370,0.0036,0.0817,0.6535,1,0.4708,0.1680,0.4518,27500,9993
Southwest University of Visual Arts-Tucson,Tucson,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,161.0,...,0.0000,0.0000,0.1491,0.2795,1,0.4469,0.4292,0.8657,27200,49750
University of Arizona,Tucson,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,32646.0,...,0.0419,0.0574,0.0096,0.1012,1,0.3349,0.4055,0.0910,44000,19000
Arizona Western College,Yuma,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,7218.0,...,0.0109,0.0313,0.0296,0.6550,1,0.5581,0.0469,0.3166,27000,5500
Arizona State University-Tempe,Tempe,AZ,0.0,0.0,0.0,0,565.0,580.0,0.0,39316.0,...,0.0401,0.0942,0.0083,0.0902,1,0.3192,0.4527,0.1414,45100,20229

In [17]:
college.iloc[[60, 99, 3], :].index.tolist()

['University of Alaska Anchorage',
 'International Academy of Hair Design',
 'University of Alabama in Huntsville']

In [18]:
college.iloc[:3, :4]

                                           CITY STABBR  HBCU  MENONLY
INSTNM
Alabama A & M University                 Normal     AL   1.0      0.0
University of Alabama at Birmingham  Birmingham     AL   0.0      0.0
Amridge University                   Montgomery     AL   0.0      0.0

In [20]:
college.iloc[:, [4, 6]].columns

Index(['WOMENONLY', 'SATVRMID'], dtype='object')

In [21]:
college.iloc[5, -4]

0.401

In [22]:
col_start = college.columns.get_loc('UGDS_WHITE')
col_end = college.columns.get_loc('UGDS_UNKN') + 1
col_start, col_end

(10, 19)

In [23]:
college.iloc[:5, col_start:col_end]

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,0.0333,0.9353,0.0055,0.0019,0.0024,0.0019,0.0000,0.0059,0.0138
University of Alabama at Birmingham,0.5922,0.2600,0.0283,0.0518,0.0022,0.0007,0.0368,0.0179,0.0100
Amridge University,0.2990,0.4192,0.0069,0.0034,0.0000,0.0000,0.0000,0.0000,0.2715
University of Alabama in Huntsville,0.6988,0.1255,0.0382,0.0376,0.0143,0.0002,0.0172,0.0332,0.0350
Alabama State University,0.0158,0.9208,0.0121,0.0019,0.0010,0.0006,0.0098,0.0243,0.0137

In [24]:
row_start = college.index[10]
row_end = college.index[15]
college.loc[row_start:row_end, 'UGDS_WHITE']

INSTNM
Birmingham Southern College                 0.7983
Chattahoochee Valley Community College      0.4661
Concordia College Alabama                   0.0280
South University-Montgomery                 0.3046
Enterprise State Community College          0.6408
James H Faulkner State Community College    0.6979
Name: UGDS_WHITE, dtype: float64

In [25]:
college = college.sort_index()
college.head()

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
A & W Healthcare Educators,New Orleans,LA,0.0,0.0,0.0,0,NaN,NaN,0.0,40.0,...,0.0000,0.0000,0.0000,0.1250,1,0.7018,0.8596,0.6667,NaN,19022.5
A T Still University of Health Sciences,Kirksville,MO,0.0,0.0,0.0,0,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,219800,PrivacySuppressed
ABC Beauty Academy,Garland,TX,0.0,0.0,0.0,0,NaN,NaN,0.0,30.0,...,0.0000,0.0000,0.0000,0.0000,0,0.7857,0.0000,0.8286,NaN,PrivacySuppressed
ABC Beauty College Inc,Arkadelphia,AR,0.0,0.0,0.0,0,NaN,NaN,0.0,38.0,...,0.0000,0.0000,0.0000,0.2105,1,0.9815,1.0000,0.4688,PrivacySuppressed,16500
AI Miami International University of Art and Design,Miami,FL,0.0,0.0,0.0,0,NaN,NaN,0.0,2778.0,...,0.0018,0.0025,0.4644,0.2185,1,0.5507,0.6966,0.3262,29900,31000

In [26]:
college.loc['Sp':'Su', 'UGDS_WHITE']

INSTNM
Spa Tech Institute-Ipswich                    0.9459
Spa Tech Institute-Plymouth                   0.7124
Spa Tech Institute-Westboro                   0.8222
Spa Tech Institute-Westbrook                  0.9417
Spalding University                           0.6650
                                               ...
Studio Academy of Beauty                      0.4669
Studio Jewelers                               0.2545
Stylemaster College of Hair Design            0.9481
Styles and Profiles Beauty College            0.8710
Styletrends Barber and Hairstyling Academy    0.0000
Name: UGDS_WHITE, Length: 201, dtype: float64

In [27]:
college.index.is_monotonic_increasing

True